import { Category, Product, PromoCode, ComboDeal } from "./types";

export const INITIAL_CATEGORIES: Category[] = [
  { id: "fruits", name: "Fruits", iconName: "Apple" },
  { id: "vegetables", name: "Vegetables", iconName: "Leaf" },
  { id: "dairy", name: "Dairy & Eggs", iconName: "Milk" },
  { id: "snacks", name: "Snacks", iconName: "Cookie" },
  { id: "beverages", name: "Cold Drinks", iconName: "CupSoda" },
  { id: "bakery", name: "Bakery", iconName: "Croissant" },
  { id: "personal-care", name: "Personal Care", iconName: "Sparkles" },
  { id: "household", name: "Household Essentials", iconName: "Home" },
  { id: "frozen", name: "Frozen Food", iconName: "FlameKindling" }, // standing in for cold/ice
  { id: "baby", name: "Baby Care", iconName: "Baby" },
  { id: "pet", name: "Pet Care", iconName: "Dog" },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Fruits
  {
    id: "f1",
    name: "Fresh Robusta Bananas",
    brand: "Orchard Fresh",
    category: "fruits",
    weight: "1 kg (approx 5-6 units)",
    marketPrice: 70,
    sellingPrice: 55,
    discount: 21,
    stock: 45,
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&q=80&w=400",
    description: "Picked at peak ripeness, our Robusta bananas are naturally sweet, creamy, and packed with energy-boosting potassium. Perfect for smoothies, oatmeal toppings, or a simple on-the-go snack.",
    isFeatured: true,
    isBestOffer: true,
    rating: 4.8,
    ratingCount: 320,
  },
  {
    id: "f2",
    name: "Royal Gala Red Apples",
    brand: "Premium Imports",
    category: "fruits",
    weight: "4 units (approx 650g)",
    marketPrice: 180,
    sellingPrice: 145,
    discount: 19,
    stock: 25,
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=400",
    description: "Crisp and delightfully sweet dessert apples imported from top orchards. Red Royal Gala apples offer thin skin, rich texture, and a aromatic sweet bite.",
    nutrition: { calories: "95 kcal", protein: "0.5 g", carbs: "25 g", fat: "0.3 g" },
    isFeatured: true,
    isBestOffer: false,
    rating: 4.6,
    ratingCount: 142,
  },
  {
    id: "f3",
    name: "Alphonso Mangoes (Semi-Ripe)",
    brand: "Ratnagiri Farms",
    category: "fruits",
    weight: "2 units (approx 500g)",
    marketPrice: 250,
    sellingPrice: 189,
    discount: 24,
    stock: 12,
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=400",
    description: "The King of Mangoes! Grown in the fertile volcanic soil of Ratnagiri, these premium Alphonso mangoes possess a rich saffron hue and unmatched honey-like flavor.",
    isFeatured: true,
    isBestOffer: true,
    rating: 4.9,
    ratingCount: 512,
  },

  // Vegetables
  {
    id: "v1",
    name: "Hybrid Juicy Tomatoes",
    brand: "GreenLeaf Farms",
    category: "vegetables",
    weight: "500 g",
    marketPrice: 40,
    sellingPrice: 28,
    discount: 30,
    stock: 60,
    image: "https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&q=80&w=400",
    description: "Locally grown hybrid tomatoes, firm, glossy, and filled with robust juicy sweetness. Ideal for rich curries, freshly prepared salsas, or quick summer salads.",
    isFeatured: false,
    isBestOffer: true,
    rating: 4.4,
    ratingCount: 215,
  },
  {
    id: "v2",
    name: "Farm Fresh Desi Onions",
    brand: "Nashik Farms",
    category: "vegetables",
    weight: "1 kg",
    marketPrice: 50,
    sellingPrice: 42,
    discount: 16,
    stock: 80,
    image: "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&q=80&w=400",
    description: "Pungent onions farmed carefully in the Nashik belt. Clean, dry skin with pristine, crisp layers which are essential as a base for Indian masalas.",
    isFeatured: true,
    isBestOffer: false,
    rating: 4.5,
    ratingCount: 610,
  },
  {
    id: "v3",
    name: "Organic Spinach (Palak)",
    brand: "Zesty Farms",
    category: "vegetables",
    weight: "250 g bunch",
    marketPrice: 30,
    sellingPrice: 18,
    discount: 40,
    stock: 35,
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=400",
    description: "Washed twice and ready for cooking! Iron-rich organic spinach leaves, picked early morning. Perfect for palak paneer, wholesome green juices, or healthy stir-fries.",
    nutrition: { calories: "23 kcal", protein: "2.9 g", carbs: "3.6 g", fat: "0.4 g" },
    isFeatured: false,
    isBestOffer: true,
    rating: 4.7,
    ratingCount: 94,
  },

  // Dairy & Eggs
  {
    id: "d1",
    name: "Full Cream Fresh Milk",
    brand: "Amul Gold",
    category: "dairy",
    weight: "500 ml pouch",
    marketPrice: 34,
    sellingPrice: 33,
    discount: 3,
    stock: 120,
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&q=80&w=400",
    description: "Pasteurized, creamy full cream milk with 6% fat content, suitable for boiling, making sweet curd, paneer, tea, or direct healthy consumption.",
    nutrition: { calories: "150 kcal", protein: "8 g", carbs: "12 g", fat: "8 g" },
    isFeatured: true,
    isBestOffer: false,
    rating: 4.9,
    ratingCount: 1600,
  },
  {
    id: "d2",
    name: "Salted Table Butter 100g",
    brand: "Amul Pasteurised Butter",
    category: "dairy",
    weight: "100 g",
    marketPrice: 60,
    sellingPrice: 58,
    discount: 3,
    stock: 90,
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=400",
    description: "The classic Utterly Butterly Delicious table butter. Spread smoothly over toast, toss it in parathas, or bake delicious melt-in-mouth cookies.",
    isFeatured: false,
    isBestOffer: false,
    rating: 4.9,
    ratingCount: 980,
  },
  {
    id: "d3",
    name: "Premium Farm Fresh Brown Eggs",
    brand: "Eggo Farms",
    category: "dairy",
    weight: "6 units pack",
    marketPrice: 95,
    sellingPrice: 79,
    discount: 16,
    stock: 40,
    image: "https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&q=80&w=400",
    description: "High protein, farm fresh brown eggs from hens fed with continuous organic grains. Inspected and sanitized packaging to prevent damage.",
    nutrition: { calories: "70 kcal per egg", protein: "6 g", carbs: "0.6 g", fat: "5 g" },
    isFeatured: true,
    isBestOffer: true,
    rating: 4.7,
    ratingCount: 310,
  },

  // Snacks & Munchies
  {
    id: "s1",
    name: "Sizzling Hot Potato Chips",
    brand: "Lays Maxx",
    category: "snacks",
    weight: "80 g",
    marketPrice: 40,
    sellingPrice: 36,
    discount: 10,
    stock: 150,
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d20?auto=format&fit=crop&q=80&w=400",
    description: "Deeply ridged and flavored with fiery peri-peri spices. These potato chips deliver a crunchy kick of heat, making them an incredible companion for late-night streaming.",
    ingredients: "Fresh Potatoes, Edible Vegetable Oil, Chili Spices, Salt, Acid regulators.",
    isFeatured: false,
    isBestOffer: false,
    rating: 4.3,
    ratingCount: 540,
  },
  {
    id: "s2",
    name: "Double Chocolate Chip Cookies",
    brand: "Milano Premium",
    category: "snacks",
    weight: "120 g",
    marketPrice: 120,
    sellingPrice: 99,
    discount: 17,
    stock: 55,
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&q=80&w=400",
    description: "Irresistibly crumbly cookies baked with dark cocoa powder and studded with rich Belgian dark chocolate chunks. Pure indulgence in every single bite.",
    isFeatured: true,
    isBestOffer: true,
    rating: 4.8,
    ratingCount: 220,
  },

  // Cold Drinks
  {
    id: "b1",
    name: "Classic Cola Fizzy Soda",
    brand: "Coca-Cola",
    category: "beverages",
    weight: "750 ml Pet Bottle",
    marketPrice: 45,
    sellingPrice: 40,
    discount: 11,
    stock: 140,
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=400",
    description: "Keep cold! The legendary refreshing fizzy beverage with its secret recipe. Crisp cooling flavors for any hot day or snack pairing.",
    isFeatured: false,
    isBestOffer: false,
    rating: 4.6,
    ratingCount: 1140,
  },
  {
    id: "b2",
    name: "Organic Coconut Water",
    brand: "PureNectar",
    category: "beverages",
    weight: "200 ml Tetrapack",
    marketPrice: 60,
    sellingPrice: 49,
    discount: 18,
    stock: 85,
    image: "https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&q=80&w=400",
    description: "100% natural, fresh coconut water packed directly from Coastal groves. Full of essential electrolytes, zero added sugars, and zero colors.",
    nutrition: { calories: "40 kcal", protein: "0.2 g", carbs: "9 g", fat: "0 g" },
    isFeatured: true,
    isBestOffer: true,
    rating: 4.8,
    ratingCount: 460,
  },

  // Bakery
  {
    id: "bk1",
    name: "Whole Wheat Sourdough Bread",
    brand: "The Artisanal Oven",
    category: "bakery",
    weight: "400 g loaf",
    marketPrice: 150,
    sellingPrice: 120,
    discount: 20,
    stock: 18,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=400",
    description: "Handcrafted loaf fermented naturally for 18 hours using traditional sourdough culture. Extremely chewy crust, open airy crumb, and a rustic tangy taste.",
    isFeatured: true,
    isBestOffer: false,
    rating: 4.7,
    ratingCount: 88,
  },
  {
    id: "bk2",
    name: "Flaky Belgian Chocolate Croissant",
    brand: "The Artisanal Oven",
    category: "bakery",
    weight: "1 unit (approx 100g)",
    marketPrice: 110,
    sellingPrice: 89,
    discount: 19,
    stock: 15,
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=400",
    description: "A buttery, multi-layered French yeast pastry filled to the brim with warm, molten Belgian semisweet dark chocolate ganache, baked fresh every morning.",
    isFeatured: false,
    isBestOffer: true,
    rating: 4.5,
    ratingCount: 104,
  },

  // Personal Care
  {
    id: "pc1",
    name: "Antibacterial Lemon Hand Wash",
    brand: "Dettol Shield",
    category: "personal-care",
    weight: "200 ml Refill Bottle",
    marketPrice: 99,
    sellingPrice: 85,
    discount: 14,
    stock: 75,
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&q=80&w=400",
    description: "Enriched with zesty lemon extracts, this germ-killing formula safeguards your family with continuous hygiene while replenishing skin moisture levels.",
    isFeatured: false,
    isBestOffer: false,
    rating: 4.8,
    ratingCount: 412,
  },
  {
    id: "pc2",
    name: "Soothing Organic Aloe Vera Gel",
    brand: "GreenGlow Skincare",
    category: "personal-care",
    weight: "150 g tube",
    marketPrice: 160,
    sellingPrice: 128,
    discount: 20,
    stock: 32,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400",
    description: "100% pure cold-pressed Aloe Vera juice configured into a non-sticky gel format. Hydrates dry skin instantly, cures sunburn, and softens split hair ends.",
    isFeatured: true,
    isBestOffer: true,
    rating: 4.6,
    ratingCount: 155,
  },

  // Household
  {
    id: "h1",
    name: "Zesty Lime Liquid Dishwash",
    brand: "Pril Glow",
    category: "household",
    weight: "500 ml dispenser",
    marketPrice: 120,
    sellingPrice: 105,
    discount: 12,
    stock: 50,
    image: "https://images.unsplash.com/photo-1622445218274-faf369e88aa1?auto=format&fit=crop&q=80&w=400",
    description: "A super-concentrated dishwash formula infused with thousands of real lime extracts. Tackles persistent grease smells and clears oily stains with immense speed.",
    isFeatured: false,
    isBestOffer: false,
    rating: 4.7,
    ratingCount: 290,
  },
  {
    id: "h2",
    name: "Citrus Scented Garbage Bags (Large)",
    brand: "EcoTidy Essentials",
    category: "household",
    weight: "30 bags roll",
    marketPrice: 140,
    sellingPrice: 112,
    discount: 20,
    stock: 70,
    image: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=400",
    description: "Heavy-duty biodegradable garbage bags equipped with tie strings. Formulated with a pleasant citrus perfume that neutralizes kitchen dust and food waste odors.",
    isFeatured: true,
    isBestOffer: true,
    rating: 4.4,
    ratingCount: 182,
  },

  // Frozen Food
  {
    id: "fz1",
    name: "Crispy Golden French Fries",
    brand: "McCain Party Pack",
    category: "frozen",
    weight: "750 g big pack",
    marketPrice: 199,
    sellingPrice: 159,
    discount: 20,
    stock: 30,
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&q=80&w=400",
    description: "Premium grade thin potatoes cut uniformly, flash-frozen to lock in crunch and flavor. Deep fry or air-fry for 3-4 minutes to get delicious golden fries.",
    isFeatured: true,
    isBestOffer: false,
    rating: 4.8,
    ratingCount: 495,
  },

  // Baby Care
  {
    id: "bc1",
    name: "Pure Aloe Baby Wet Wipes",
    brand: "Huggies SoftCare",
    category: "baby",
    weight: "80 wipes pack",
    marketPrice: 180,
    sellingPrice: 139,
    discount: 22,
    stock: 45,
    image: "https://images.unsplash.com/photo-1560130803-aa6192f6f216?auto=format&fit=crop&q=80&w=400",
    description: "Pediatrician-tested ultra-gentle wet wipes for sensitive baby skin. Enriched with natural Aloe extracts, and totally free from alcohol, parabens, and chlorine.",
    isFeatured: false,
    isBestOffer: true,
    rating: 4.7,
    ratingCount: 382,
  },

  // Pet Care
  {
    id: "pt1",
    name: "Gourmet Chicken Dog Treats",
    brand: "Pedigree DeliSnacks",
    category: "pet",
    weight: "150 g",
    marketPrice: 150,
    sellingPrice: 135,
    discount: 10,
    stock: 22,
    image: "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?auto=format&fit=crop&q=80&w=400",
    description: "Extremely tasty, soft chewable bones packed with digestible proteins, helping raise healthy teeth bone density. Recommended for reward training active puppies.",
    isFeatured: true,
    isBestOffer: false,
    rating: 4.9,
    ratingCount: 172,
  }
];

export const PROMO_CODES: PromoCode[] = [
  { code: "SMART20", description: "Get ₹20 off on orders starting at ₹150", discountValue: 20, minimumOrder: 150 },
  { code: "FRESH50", description: "Save ₹50 on healthy fruits & veggies (Min cart: ₹300)", discountValue: 50, minimumOrder: 300 },
  { code: "HELLOSMART", description: "Special user welcome flat ₹100 discount (Min cart: ₹500)", discountValue: 100, minimumOrder: 500 },
];

export const COMBO_DEALS: ComboDeal[] = [
  {
    id: "combo1",
    title: "Healthy High-Fiber Breakfast Combo",
    productIds: ["f1", "bk1", "b2"], // Bananas, Wheat Sourdough, Coconut Water
    originalPrice: 280, // 55 + 120 + 49 = 224
    sellingPrice: 199,
    image: "https://images.unsplash.com/photo-1496041675317-fa287df1c998?auto=format&fit=crop&q=80&w=400",
    badge: "Save ₹25 Extra",
  },
  {
    id: "combo2",
    title: "Movie Night Crisps & Cola Binge Pack",
    productIds: ["s1", "s2", "b1"], // Chips, Cookies, Cola
    originalPrice: 175, // 36 + 99 + 40 = 175
    sellingPrice: 149,
    image: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&q=80&w=400",
    badge: "15% off Combo",
  }
];
